# model: res18_gsc
model: trans_gsc
output_dir: ./experiments/companion_png/

# data
data_type: 'diap'
gaze_data: ./data/GazeSetsPng
test_ids: [0]
input_size: [224, 224]
mirror: True
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
label_factor: 1

# train
gpu_id: 0
batch_size: 64
iter_size: 1
test_step: 0
save_step: 10
log_step: 1000
train_test: True
finetune: ./weights/best_ckpt_2702.pth.tar
stop_thresh: 0.78
with_la: True
companion: True
warmup: 0
validation: False

# loss
loss: 'L1'

# schedule
epochs: 30
base_lr: 0.0001
scheduler_type: exp
lr_milestones: [1, 10, 13]
lr_stepsize: 10
gamma: 0.96

# optimizer
optimizer: adamw
weight_decay: 0.05

# test
test_label: True
test_batch_size: 64
test_model: ''
