# model: res18_gsc
model: gazeformer
output_dir: ./experiments/single_png/

# data
data_type: 'mpii'
gaze_data: ./data/GazeSetsPng
test_ids: [0]
input_size: [224, 224]
mirror: True
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
label_factor: 1

# train
gpu_id: 0
batch_size: 64
iter_size: 1
test_step: 0
save_step: 5
log_step: 1000
train_test: True
# finetune: weights/trans_final_ckpt.pth.tar
stop_thresh: 0.78
with_la: False
companion: False
warmup: 3

# loss
loss: 'L1'

# schedule
epochs: 30
base_lr: 0.0001
scheduler_type: exp
lr_milestones: [1, 10, 13]
lr_stepsize: 10
gamma: 0.95

# optimizer
optimizer: adamw
weight_decay: 0.01

# test
test_label: True
test_batch_size: 64
test_model: ''
